//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            this.EmployeSessionKPIs = new HashSet<EmployeSessionKPI>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<EmployeSessionKPI> EmployeSessionKPIs { get; set; }
    }
}
