//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPAMSEntities : DbContext
    {
        internal object Session;

        public EPAMSEntities()
            : base("name=EPAMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Course> Courses { get; set; }
        public DbSet<CourseAllocation> CourseAllocations { get; set; }
        public DbSet<EmployeeType> EmployeeTypes { get; set; }
        public DbSet<EmployeSessionKPI> EmployeSessionKPIs { get; set; }
        public DbSet<Enrollment> Enrollments { get; set; }
        public DbSet<KPI> KPIs { get; set; }
        public DbSet<KPIScore> KPIScores { get; set; }
        public DbSet<PeerEvaluation> PeerEvaluations { get; set; }
        public DbSet<PeerEvaluator> PeerEvaluators { get; set; }
        public DbSet<Questionare> Questionares { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<SessionKPIWeight> SessionKPIWeights { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentEvaluation> StudentEvaluations { get; set; }
        public DbSet<SubKPI> SubKPIs { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<User> Users { get; set; }
        public object Student { get; internal set; }
        public object Course { get; internal set; }
        public object Teacher { get; internal set; }
    }
}
