//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionare
    {
        public Questionare()
        {
            this.PeerEvaluations = new HashSet<PeerEvaluation>();
            this.StudentEvaluations = new HashSet<StudentEvaluation>();
        }
    
        public int id { get; set; }
        public string question { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<PeerEvaluation> PeerEvaluations { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluations { get; set; }
    }
}
