//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.CourseAllocations = new HashSet<CourseAllocation>();
            this.Enrollments = new HashSet<Enrollment>();
            this.PeerEvaluators = new HashSet<PeerEvaluator>();
            this.SessionKPIWeights = new HashSet<SessionKPIWeight>();
            this.Students = new HashSet<Student>();
            this.EmployeSessionKPIs = new HashSet<EmployeSessionKPI>();
            this.StudentEvaluations = new HashSet<StudentEvaluation>();
            this.PeerEvaluations = new HashSet<PeerEvaluation>();
            this.SocietyAssignments = new HashSet<SocietyAssignment>();
            this.SocietyEvaluations = new HashSet<SocietyEvaluation>();
            this.CHRs = new HashSet<CHR>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<CourseAllocation> CourseAllocations { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<PeerEvaluator> PeerEvaluators { get; set; }
        public virtual ICollection<SessionKPIWeight> SessionKPIWeights { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<EmployeSessionKPI> EmployeSessionKPIs { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluations { get; set; }
        public virtual ICollection<PeerEvaluation> PeerEvaluations { get; set; }
        public virtual ICollection<SocietyAssignment> SocietyAssignments { get; set; }
        public virtual ICollection<SocietyEvaluation> SocietyEvaluations { get; set; }
        public virtual ICollection<CHR> CHRs { get; set; }
    }
}
