//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society
    {
        public Society()
        {
            this.SocietyAssignments = new HashSet<SocietyAssignment>();
        }
    
        public int SocietyId { get; set; }
        public string SocietyName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SocietyAssignment> SocietyAssignments { get; set; }
    }
}
