//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyAssignment
    {
        public int AssignmentId { get; set; }
        public string TeacherId { get; set; }
        public int SocietyId { get; set; }
        public int SessionId { get; set; }
        public Nullable<bool> IsChairperson { get; set; }
        public Nullable<bool> IsMentor { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Society Society { get; set; }
        public virtual User User { get; set; }
    }
}
