//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.StudentEvaluations = new HashSet<StudentEvaluation>();
        }
    
        public string userID { get; set; }
        public string name { get; set; }
        public Nullable<int> admissionSessionID { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<StudentEvaluation> StudentEvaluations { get; set; }
    }
}
