//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubKPI
    {
        public SubKPI()
        {
            this.EmployeSessionKPIs = new HashSet<EmployeSessionKPI>();
            this.SessionKPIWeights = new HashSet<SessionKPIWeight>();
        }
    
        public int id { get; set; }
        public Nullable<int> KPIID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<EmployeSessionKPI> EmployeSessionKPIs { get; set; }
        public virtual KPI KPI { get; set; }
        public virtual ICollection<SessionKPIWeight> SessionKPIWeights { get; set; }
    }
}
