//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.CourseAllocations = new HashSet<CourseAllocation>();
            this.Enrollments = new HashSet<Enrollment>();
            this.PeerEvaluations = new HashSet<PeerEvaluation>();
            this.PeerEvaluators = new HashSet<PeerEvaluator>();
        }
    
        public string userID { get; set; }
        public string name { get; set; }
        public string department { get; set; }
    
        public virtual ICollection<CourseAllocation> CourseAllocations { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<PeerEvaluation> PeerEvaluations { get; set; }
        public virtual ICollection<PeerEvaluator> PeerEvaluators { get; set; }
        public virtual User User { get; set; }
    }
}
