//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.KPIScores = new HashSet<KPIScore>();
            this.KPIScores1 = new HashSet<KPIScore>();
        }
    
        public string id { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string profileImagePath { get; set; }
        public Nullable<int> isActive { get; set; }
    
        public virtual ICollection<KPIScore> KPIScores { get; set; }
        public virtual ICollection<KPIScore> KPIScores1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
